"""生成示例报表（含真实场景中常见的脏数据），用于验证解析与异常处理。"""
import csv
import os
import random
from datetime import date, timedelta

OUT = os.path.dirname(os.path.abspath(__file__))
random.seed(42)
START = date(2026, 8, 1)
DAYS = 30

CAMPAIGNS = [
    ("CUR-Auto-Discovery", "自动发现", "Auto"),
    ("CUR-Core-Exact", "核心精准", "Exact"),
    ("CUR-LongTail-Phrase", "长尾词组", "Phrase"),
]

KW_POOL = {
    "Auto": [("auto-targeting-1", "AUTO")],
    "Exact": [("shower curtain", "EXACT"), ("fabric shower curtain", "EXACT"),
              ("waterproof shower curtain", "EXACT"), ("hotel style shower curtain", "EXACT")],
    "Phrase": [("bathroom curtain 72 inch", "PHRASE"), ("mold resistant shower liner", "PHRASE"),
               ("clear shower curtain", "PHRASE"), ("shower curtain with hooks", "PHRASE")],
}

# 人为设定的表现差异，用于让规则引擎有真实结论可出
PERF = {
    "shower curtain": (0.42, 0.09, 1.35),            # 大词：高 CTR，CVR 一般，CPC 高
    "fabric shower curtain": (0.55, 0.14, 1.05),
    "waterproof shower curtain": (0.50, 0.12, 1.10),
    "hotel style shower curtain": (0.48, 0.16, 0.95),
    "bathroom curtain 72 inch": (0.38, 0.11, 0.80),
    "mold resistant shower liner": (0.52, 0.15, 0.85),
    "clear shower curtain": (0.22, 0.03, 0.95),      # 低效词
    "shower curtain with hooks": (0.45, 0.13, 0.90),
    "auto-targeting-1": (0.30, 0.06, 0.75),
}

ST_POOL = ["fabric shower curtain 72", "waterproof fabric shower liner", "shower curtain rings 12",
           "black shower curtain", "waffle weave shower curtain", "shower curtain for clawfoot tub",
           "bathroom curtains clearance", "hotel collection shower curtain", "peva shower liner",
           "shower curtain magnets"]


def w(path, rows):
    with open(os.path.join(OUT, path), "w", encoding="utf-8-sig", newline="") as f:
        csv.writer(f).writerows(rows)


# ---------------------------------------------------------------- 1. SP 关键词报表
rows = [["Sponsored Products Campaign Report", "Generated by Amazon Advertising"],
        ["Report period", f"{START} - {START + timedelta(days=DAYS-1)}", "Currency: USD"],
        [],
        ["Date", "Campaign Name", "Ad Group Name", "Keyword", "Match Type",
         "Impressions", "Clicks", "Spend", "Orders", "Sales"]]
for i in range(DAYS):
    d = START + timedelta(days=i)
    dow_factor = 1.25 if d.weekday() in (5, 6) else 1.0
    for camp, ag, mt in CAMPAIGNS:
        for kw, mtype in KW_POOL[mt]:
            ctr, cvr, cpc = PERF[kw]
            imp = int(random.randint(2000, 6000) * dow_factor)
            clk = max(0, int(imp * ctr / 100 * random.uniform(0.8, 1.2)))
            orders = int(clk * cvr * random.uniform(0.7, 1.3))
            if kw == "clear shower curtain":
                orders = 0                                  # 高花费零订单
            spend = round(clk * cpc * random.uniform(0.85, 1.15), 2)
            price = round(random.uniform(18.9, 27.9), 2)
            sales = round(orders * price, 2)
            rows.append([d.isoformat(), camp, ag, kw, mtype, imp, clk, spend, orders, sales])
# 故意注入的脏数据
rows.append(["8/15/2026", "CUR-Core-Exact", "核心精准", "shower curtain", "EXACT", 1200, 18, 21.4, 2, 45.8])
rows.append([(START + timedelta(days=3)).isoformat(), "CUR-LongTail-Phrase", "长尾词组",
             "clear shower curtain", "PHRASE", 900, "", "12.30", 0, "0"])
rows.append([(START + timedelta(days=4)).isoformat(), "CUR-Auto-Discovery", "自动发现",
             "auto-targeting-1", "AUTO", 500, 6, "-3.20", 0, 0])
rows.append([(START + timedelta(days=5)).isoformat(), "CUR-Core-Exact", "核心精准",
             "fabric shower curtain", "EXACT", "", 0, 0, 0, 0])
rows.append([(START + timedelta(days=5)).isoformat(), "CUR-Core-Exact", "核心精准",
             "fabric shower curtain", "EXACT", 1100, 22, 23.1, 3, 68.4])   # 重复行
w("sp_keyword_report.csv", rows)

# ---------------------------------------------------------------- 2. 搜索词报表
rows = [["Sponsored Products Search Term Report"], [],
        ["Date", "Campaign Name", "Ad Group Name", "Customer Search Term", "Match Type",
         "Impressions", "Clicks", "Spend", "Orders", "Sales"]]
for i in range(DAYS):
    d = START + timedelta(days=i)
    for term in ST_POOL:
        if random.random() < 0.55:
            continue
        imp = random.randint(200, 1800)
        good = term not in ("shower curtain rings 12", "bathroom curtains clearance")
        ctr = random.uniform(0.25, 0.6) if good else random.uniform(0.15, 0.35)
        clk = int(imp * ctr / 100)
        orders = int(clk * random.uniform(0.08, 0.18)) if good else 0
        spend = round(clk * random.uniform(0.6, 1.2), 2)
        sales = round(orders * random.uniform(18, 28), 2)
        rows.append([d.isoformat(), "CUR-Auto-Discovery", "自动发现", term, "AUTO",
                     imp, clk, spend, orders, sales])
w("sp_search_term_report.csv", rows)

# ---------------------------------------------------------------- 3. 业务报告（TACOS 分母 + 库存）
rows = [["Business Report - Detail Page Sales and Traffic by Child Item"], [],
        ["Date", "ASIN", "Sessions", "Page Views", "Units Ordered", "Total Order Items",
         "Ordered Product Sales", "Available Inventory"]]
inventory = 3200
for i in range(DAYS):
    d = START + timedelta(days=i)
    for asin in ("B0C1", "B0C2"):
        sess = random.randint(420, 980)
        units = int(sess * random.uniform(0.03, 0.07))
        inventory = max(0, inventory - units + (900 if i == 10 else 0))
        rows.append([d.isoformat(), asin, sess, sess * 2, units,
                     int(units * 0.95), round(units * random.uniform(19, 28), 2), inventory])
w("business_report.csv", rows)

# ---------------------------------------------------------------- 4. ABA
rows = [["Amazon Brand Analytics - Search Query Performance"], [],
        ["Search Term", "Search Frequency Rank", "#1 Clicked ASIN", "#1-#3 Click Share",
         "#1-#3 Conversion Share", "Week Ending"]]
aba_terms = ["shower curtain", "fabric shower curtain", "waterproof shower curtain",
             "shower curtain liner", "hotel shower curtain", "waffle shower curtain",
             "black shower curtain", "shower curtain with hooks", "72 inch shower curtain",
             "mold resistant shower curtain", "clear shower liner", "bathroom curtain set",
             "shower curtain rings", "luxury shower curtain", "peva shower curtain liner"]
for i, t in enumerate(aba_terms):
    rows.append([t, (i + 1) * 7 + random.randint(0, 5), f"B0X{random.randint(1000000,9999999)}",
                 round(random.uniform(0.18, 0.62), 4), round(random.uniform(0.12, 0.55), 4),
                 (START + timedelta(days=27)).isoformat()])
w("aba_search_terms.csv", rows)

# ---------------------------------------------------------------- 5. BR 品牌指标
rows = [["Brand Metrics Report"], [],
        ["Date", "ASIN", "Brand Search Volume", "New-to-Brand Orders", "New-to-Brand %",
         "Repeat Purchase %"]]
for i in range(DAYS):
    d = START + timedelta(days=i)
    for asin in ("B0C1", "B0C2"):
        v = random.randint(300, 900)
        ntb = int(v * random.uniform(0.25, 0.45))
        rows.append([d.isoformat(), asin, v, ntb, round(ntb / max(v, 1) * 100, 2),
                     round(random.uniform(6, 18), 2)])
w("brand_metrics_report.csv", rows)

print("示例报表已生成到：", OUT)
for f in sorted(os.listdir(OUT)):
    if f.endswith(".csv"):
        print(" -", f, os.path.getsize(os.path.join(OUT, f)), "bytes")
